// PixelPal Purchases v2 compatibility/enrichment layer.
// v3 owns Bank + Review interaction. This file now only provides state migration helpers.
const _settingsV1=settingsView,_renderV1=render;
const purposeEmoji=p=>({my_purchase:'👤',house_purchase:'🏠',gift:'🎁',other:'🧩'}[p]||'❔');
function inferredPurposeV2(prod){const s=productStats().get(prod.id);if(!s)return 'other';const f=[...s.funding];if(f.length&&f.every(x=>/Adam|Geek|Flex|Clothing/i.test(x)))return 'my_purchase';if(f.length&&f.every(x=>/Household|joint/i.test(x)))return 'house_purchase';return 'other'}
function ensureV2(){state.people=state.people||[];state.bankTransactions=state.bankTransactions||[];for(const p of state.products||[]){if(!p.purpose)p.purpose=inferredPurposeV2(p)}}
nav=function(){return `<header class="topbar"><a class="brand" href="#/"><span class="pixel">👾</span><span><b>Purchases</b><small>PixelPalOS Lab</small></span></a><button class="iconbtn" id="menuBtn" aria-label="Menu">☰</button></header><nav class="tabs" id="nav"><a href="#/" data-route="/">🏠<span>Home</span></a><a href="#/review" data-route="/review">🧪<span>Review</span></a><a href="#/purchases" data-route="/purchases">🧾<span>Purchases</span></a><a href="#/bank" data-route="/bank">🏦<span>Bank</span></a><a href="#/products" data-route="/products">📦<span>Products</span></a><a href="#/assets" data-route="/assets">🎒<span>Assets</span></a><a href="#/settings" data-route="/settings">⚙️<span>Settings</span></a></nav>`}
settingsView=function(){const base=_settingsV1();return base.replace('</main>',`<section class="card"><h2>Historic evidence</h2><p><b>${state.bankTransactions?.length||0}</b> Monzo transactions are stored in this private local dataset. They are evidence alongside purchases, not assumed to be itemised receipts.</p><p><b>${state.people?.length||0}</b> people are available for gift tagging.</p></section></main>`)}
render=async function(){if(state)ensureV2();return _renderV1()};
